### ISSUE TITLE
账号和密码不对啊

### ISSUE THREAD

**Issue by Crisfw** [lyric777/Book-Management-System-V2#1]
作者能不能告知下账号和密码呢

**Comment by libryz** [comment]
![微信图片_20201130103248](https://user-images.githubusercontent.com/52672041/100562715-766b8180-32f7-11eb-86ae-3a5ee9b406db.png)

**Comment by lyric777** [comment]
感谢楼上

**Comment by Crisfw** [comment]
已收到邮件，我会尽快回信的

**Comment by hzh-hzh** [comment]
我遇到同样的问题，无法登录，提示账号密码错误，但是我已经输入 李华 和 1234 来登录了，是环境的问题吗？我应该如何来安装环境呢？

**Comment by Crisfw** [comment]
已收到邮件，我会尽快回信的
