### ISSUE TITLE
借阅卡到期

### ISSUE THREAD

**Issue by rattlesnakey** [lyric777/Book-Management-System-V2#2]
请问借阅卡的期限怎么修改呢？
作者是否有之前创建sqlite数据库的源代码呢？谢谢

**Comment by lyric777** [comment]
（我知道现在回复有点迟了），到期是因为确实到期了，我设置的应该都是2020年左右到期的，在数据库里直接改，建sqlite的命令我也没存，在网上查一下吧

**Comment by lyric777** [comment]
（我知道现在回复有点迟了），到期是因为确实到期了，我设置的应该都是2020年左右到期的，在数据库里直接改，建sqlite的命令我也没存，在网上查一下吧
